import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { PageProps } from '@/types';
import { Head, Link, router } from '@inertiajs/react';
import { ChevronRight, Filter, Search, X } from 'lucide-react';
import { FormEvent, useState } from 'react';

type RecordType = { id: number; request_number: string; request_type: string; status: string; request_date: string | null; prioritized: boolean; target_state: string; customer?: { institution_name: string; crm_number: string } };
type Props = PageProps & { requests: { data: RecordType[] }; filters: { search?: string; status?: string; prioritized?: string } };
const targetStyle: Record<string, string> = { LATE: 'bg-red-50 text-red-700 border-red-200', DUE_TODAY: 'bg-amber-50 text-amber-800 border-amber-200', ON_TRACK: 'bg-emerald-50 text-emerald-700 border-emerald-200', DONE: 'bg-slate-100 text-slate-600 border-slate-200' };
const statusStyle: Record<string, string> = { NEW: 'bg-blue-50 text-blue-700', UNDER_REVIEW: 'bg-amber-50 text-amber-800', APPROVED: 'bg-emerald-50 text-emerald-700', PROCESSING: 'bg-violet-50 text-violet-700', COMPLETED: 'bg-slate-100 text-slate-600', REJECTED: 'bg-red-50 text-red-700' };
const targetLabel = (state: string) => state === 'DUE_TODAY' ? 'Harus selesai hari ini' : state === 'LATE' ? 'Terlambat' : state === 'DONE' ? 'Selesai' : 'Sesuai target';
function Badge({ value, style }: { value: string; style: Record<string, string> }) { return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-bold ${style[value] ?? 'border-slate-200 bg-slate-50 text-slate-700'}`}>{value}</span>; }
function TargetBadge({ state }: { state: string }) { return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-bold ${targetStyle[state] ?? 'border-slate-200 bg-slate-50 text-slate-700'}`}>{targetLabel(state)}</span>; }

export default function Index({ requests, filters }: Props) {
    const [search, setSearch] = useState(filters.search ?? '');
    const [status, setStatus] = useState(filters.status ?? '');
    const [prioritized, setPrioritized] = useState(filters.prioritized ?? '');
    const filter = (event: FormEvent) => { event.preventDefault(); router.get('/requests', { search, status, prioritized }, { preserveState: true, replace: true }); };
    const reset = () => { setSearch(''); setStatus(''); setPrioritized(''); router.get('/requests'); };
    return <AuthenticatedLayout header={<div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-sky-700">RFID Operations</p><h1 className="text-lg font-semibold">Antrean pengajuan</h1></div>}>
        <Head title="Antrean pengajuan" />
        <div className="mx-auto max-w-7xl space-y-5">
            <div><h2 className="text-2xl font-semibold">Antrean pengajuan</h2><p className="mt-1 text-sm text-slate-500">Utama lebih dulu, lalu target hari ini/terlambat, tanggal permintaan lama.</p></div>
            <form onSubmit={filter} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-sm lg:grid-cols-[1fr_170px_170px_auto]"><label className="relative"><span className="sr-only">Cari nomor, pelanggan, atau CRM</span><Search aria-hidden="true" className="absolute left-3 top-3 text-slate-400" size={17} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari nomor, pelanggan, atau CRM" className="h-11 w-full rounded-lg border-slate-200 pl-10 text-sm" /></label><label><span className="sr-only">Status</span><select aria-label="Status" value={status} onChange={(e) => setStatus(e.target.value)} className="h-11 w-full rounded-lg border-slate-200 text-sm"><option value="">Semua status</option>{['NEW', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'PROCESSING', 'COMPLETED'].map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="sr-only">Urutan</span><select aria-label="Utamakan" value={prioritized} onChange={(e) => setPrioritized(e.target.value)} className="h-11 w-full rounded-lg border-slate-200 text-sm"><option value="">Semua urutan</option><option value="true">Utama</option><option value="false">Biasa</option></select></label><div className="flex gap-2"><button className="inline-flex h-11 flex-1 items-center justify-center gap-2 rounded-lg bg-[#173f78] px-4 text-sm font-bold text-white"><Filter size={16} />Terapkan</button><button type="button" onClick={reset} className="inline-flex h-11 items-center justify-center rounded-lg border border-slate-200 px-3 text-slate-500" aria-label="Reset filter"><X size={17} /></button></div></form>
            {requests.data.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">Tidak ada pengajuan yang cocok.</div> : <><div className="grid gap-3 md:hidden">{requests.data.map((record) => <Link key={record.id} href={`/requests/${record.id}`} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{record.request_number}</p><p className="mt-1 text-sm text-slate-600">{record.customer?.institution_name ?? '—'}</p></div><ChevronRight aria-hidden="true" size={18} className="mt-1 shrink-0 text-slate-400" /></div><div className="mt-3 flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${record.prioritized ? 'bg-blue-50 text-blue-800' : 'bg-slate-50 text-slate-700'}`}>{record.prioritized ? 'Utama' : 'Biasa'}</span><TargetBadge state={record.target_state} /><Badge value={record.status} style={statusStyle} /></div><p className="mt-3 text-xs text-slate-500">Tanggal permintaan: {record.request_date ?? '—'}</p></Link>)}</div><div className="hidden overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm md:block"><table className="w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Pengajuan</th><th className="px-4 py-3">Pelanggan</th><th className="px-4 py-3">Urutan</th><th className="px-4 py-3">Target</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{requests.data.map((record) => <tr key={record.id}><td className="px-5 py-4"><p className="font-bold">{record.request_number}</p><p className="mt-1 text-xs text-slate-500">{record.request_type.replaceAll('_', ' ')}</p></td><td className="px-4 py-4"><p className="font-medium">{record.customer?.institution_name ?? '—'}</p><p className="mt-1 text-xs text-slate-500">CRM {record.customer?.crm_number ?? '—'}</p></td><td className="px-4 py-4 font-semibold">{record.prioritized ? 'Utama' : 'Biasa'}</td><td className="px-4 py-4"><TargetBadge state={record.target_state} /></td><td className="px-4 py-4"><Badge value={record.status} style={statusStyle} /></td><td className="px-4 py-4 text-right"><Link className="inline-flex min-h-11 min-w-11 items-center justify-center" href={`/requests/${record.id}`} aria-label={`Tinjau ${record.request_number}`}><ChevronRight aria-hidden="true" size={18} /></Link></td></tr>)}</tbody></table></div></>}
        </div>
    </AuthenticatedLayout>;
}
