import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

type Event = { id: number; action: string; auditable_type: string; auditable_id: number; actor?: { name?: string }; created_at: string };
type Page = { data: Event[]; current_page: number; last_page: number };
export default function AuditIndex({ events, filters }: { events: Page; filters: { search?: string; category?: string } }) {
    const [search, setSearch] = useState(filters.search ?? ''); const [category, setCategory] = useState(filters.category ?? '');
    const submit = (event: FormEvent) => { event.preventDefault(); router.get('/audit', { search, category }, { preserveState: true, replace: true }); };
    return <AuthenticatedLayout header={<h1 className="text-lg font-semibold">Aktivitas</h1>}><Head title="Aktivitas" /><div className="mx-auto max-w-7xl space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-2xl font-bold">Aktivitas operasional</h2><p className="mt-1 text-sm text-slate-500">Filter jejak tindakan berdasarkan fitur.</p></section><section className="rounded-xl border border-slate-200 bg-white"><form onSubmit={submit} className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row"><input value={search} onChange={(event) => setSearch(event.target.value)} className="min-h-11 flex-1 rounded-lg border-slate-300 text-sm" placeholder="Cari tindakan atau ID" aria-label="Cari aktivitas" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="min-h-11 rounded-lg border-slate-300 text-sm" aria-label="Kategori aktivitas"><option value="">Semua fitur</option><option value="request">Pengajuan</option><option value="inventory">Inventory</option><option value="procurement">Pengadaan</option><option value="report">Report</option><option value="settings">Pengaturan</option></select><button className="min-h-11 rounded-lg bg-[#173f78] px-5 text-sm font-bold text-white">Terapkan</button></form><div className="divide-y divide-slate-100">{events.data.map((event) => <article key={event.id} className="flex flex-col gap-2 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{event.action}</p><p className="text-sm text-slate-500">{event.auditable_type.split('\\').pop()} #{event.auditable_id} · {event.actor?.name ?? 'Sistem'}</p></div><time className="text-xs text-slate-500">{event.created_at}</time></article>)}{events.data.length === 0 && <p className="p-10 text-center text-sm text-slate-500">Belum ada aktivitas.</p>}</div>{events.last_page > 1 && <div className="flex gap-2 border-t border-slate-100 p-4"><Link href={`/audit?page=${Math.max(1, events.current_page - 1)}`} className="rounded-lg border px-3 py-2 text-sm">Sebelumnya</Link><Link href={`/audit?page=${Math.min(events.last_page, events.current_page + 1)}`} className="rounded-lg border px-3 py-2 text-sm">Berikutnya</Link></div>}</section></div></AuthenticatedLayout>;
}
