import { Head } from '@inertiajs/react';
import axios from 'axios';
import { Download, FileText, Search, Upload } from 'lucide-react';
import { ChangeEvent, FormEvent, ReactNode, useState } from 'react';

type Props = { trackingOnly?: boolean };
type Result = { request_number: string; tracking_code: string; status: string };
type Tracking = { request_number?: string; status?: string; status_history?: { status?: string; created_at?: string }[] };

function UploadField({ name, accept, label, icon, required = false }: { name: string; accept: string; label: string; icon: ReactNode; required?: boolean }) {
    const [fileName, setFileName] = useState('Belum ada berkas');
    const onChange = (event: ChangeEvent<HTMLInputElement>) => setFileName(event.target.files?.[0]?.name ?? 'Belum ada berkas');
    return <div><label htmlFor={name} className="grid min-h-12 cursor-pointer grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-bold leading-5 text-[#173f78] transition-colors hover:border-[#173f78] focus-within:ring-2 focus-within:ring-[#173f78] focus-within:ring-offset-2">{icon}<span className="min-w-0 break-words">{label}</span><span className="shrink-0 whitespace-nowrap rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600">Pilih berkas</span></label><input id={name} required={required} type="file" accept={accept} name={name} onChange={onChange} className="sr-only" /><p className="mt-2 truncate text-xs text-slate-500" aria-live="polite">{fileName}</p></div>;
}

export default function RequestPortal({ trackingOnly = false }: Props) {
    const [english, setEnglish] = useState(false); const [tab, setTab] = useState<'submit' | 'track'>(trackingOnly ? 'track' : 'submit'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<Result | null>(null); const [tracking, setTracking] = useState<Tracking | null>(null);
    const text = english ? { title: 'RFID Card Data Change Request', intro: 'Submit a request or track its status.', submit: 'Send request', track: 'Track request', institution: 'Institution name', crm: 'CRM number', type: 'Card type', quantity: 'Required quantity', date: 'Request date', application: 'Upload RFID Application Template', payment: 'Upload Payment Proof', number: 'Request number', code: 'Tracking code', send: 'Track request', template: 'Download RFID Application Template', success: 'Request submitted successfully', submitError: 'Validation failed. Check the data and files.', trackError: 'Request not found.', empty: 'No status history yet.', status: 'Current status', info: 'Request information', documents: 'Supporting documents' } : { title: 'Pengajuan Perubahan Data Kartu RFID', intro: 'Kirim pengajuan baru atau lacak status pengajuan.', submit: 'Kirim Pengajuan', track: 'Lacak Pengajuan', institution: 'Nama institusi', crm: 'Nomor CRM', type: 'Jenis kartu', quantity: 'Jumlah kebutuhan', date: 'Tanggal permintaan', application: 'Upload Template Pengajuan RFID', payment: 'Upload Bukti Bayar', number: 'Nomor pengajuan', code: 'Kode tracking', send: 'Lacak Pengajuan', template: 'Unduh Template Pengajuan RFID', success: 'Pengajuan berhasil dikirim', submitError: 'Validasi gagal. Periksa data dan berkas.', trackError: 'Pengajuan tidak ditemukan.', empty: 'Belum ada riwayat status.', status: 'Status saat ini', info: 'Informasi Pengajuan', documents: 'Dokumen Pendukung' };
    const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); try { const response = await axios.post('/api/public/v1/requests', new FormData(event.currentTarget), { headers: { 'Idempotency-Key': crypto.randomUUID().replaceAll('-', '') } }); setResult(response.data.data); } catch (exception: any) { setError(exception.response?.data?.message ?? text.submitError); } finally { setBusy(false); } };
    const track = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); try { const response = await axios.post('/api/public/v1/tracking', { request_number: form.get('request_number'), tracking_code: form.get('tracking_code') }); setTracking(response.data.data); } catch { setError(text.trackError); } finally { setBusy(false); } };
    return <><Head title={text.title} /><main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900 sm:px-8 sm:py-10"><div className="mx-auto max-w-5xl"><header className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-blue-700">RFID Operations</p><h1 className="mt-2 max-w-3xl text-3xl font-bold tracking-tight sm:text-4xl">{text.title}</h1><p className="mt-3 text-slate-600">{text.intro}</p></div><button type="button" onClick={() => setEnglish((value) => !value)} className="min-h-11 rounded-lg border border-slate-300 bg-white px-4 text-sm font-bold transition-colors hover:border-[#173f78]" aria-label={english ? 'ID, ganti bahasa' : 'EN, ganti bahasa'}>{english ? 'ID' : 'EN'}</button></header>
    {!trackingOnly && <div className="mt-8 border-b border-slate-200" role="tablist" aria-label="Jenis aktivitas">{([{ key: 'submit', label: text.submit }, { key: 'track', label: text.track }] as const).map((item) => <button key={item.key} type="button" role="tab" aria-selected={tab === item.key} onClick={() => { setTab(item.key); setError(''); }} className={`mr-6 border-b-2 px-1 pb-3 text-sm font-bold transition-colors ${tab === item.key ? 'border-[#173f78] text-[#173f78]' : 'border-transparent text-slate-500 hover:text-slate-900'}`}>{item.label}</button>)}</div>}
    {error && <p role="alert" className="mt-5 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}{result && <section className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-5" aria-live="polite"><h2 className="font-bold text-emerald-950">{text.success}</h2><p className="mt-2 text-sm">{text.number}: <b>{result.request_number}</b></p><p className="text-sm">{text.code}: <b>{result.tracking_code}</b></p></section>}
    {!trackingOnly && tab === 'submit' && <form onSubmit={submit} className="mt-6 space-y-4"><section className="rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-500">01</p><h2 className="mt-1 text-xl font-bold">{text.info}</h2></div><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">{text.institution}<input required name="institution_name" className="mt-1 h-11 w-full rounded-lg border-slate-300" /></label><label className="block text-sm font-semibold">{text.crm}<input required name="crm_number" pattern="[A-Za-z0-9]{1,13}" className="mt-1 h-11 w-full rounded-lg border-slate-300" /></label><label className="block text-sm font-semibold">{text.type}<select required name="request_type" className="mt-1 h-11 w-full rounded-lg border-slate-300"><option value="new_card">Kartu baru</option><option value="damaged_card">Kartu rusak</option><option value="system_error_card">Kartu error system</option><option value="lost_card">Kartu hilang</option></select></label><label className="block text-sm font-semibold">{text.quantity}<input required min="1" max="10000" type="number" name="requested_quantity" className="mt-1 h-11 w-full rounded-lg border-slate-300" /></label><label className="block text-sm font-semibold sm:col-span-2">{text.date}<input required type="date" name="request_date" className="mt-1 h-11 w-full rounded-lg border-slate-300" /></label></div></section><section className="rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-500">02</p><h2 className="mt-1 text-xl font-bold">{text.documents}</h2><p className="mt-1 text-sm text-slate-500">Unduh template, isi, lalu unggah kembali bersama bukti pembayaran bila ada.</p></div><div className="grid gap-4 sm:grid-cols-2"><a href="/api/public/v1/request-template" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-emerald-700 px-3 text-sm font-bold text-white transition-colors hover:bg-emerald-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-700 focus-visible:ring-offset-2 sm:col-span-2" download><Download size={16} />{text.template}</a><UploadField name="application_file" accept=".xlsx" label={text.application} icon={<Upload size={16} />} required /><UploadField name="payment_proof" accept=".pdf,.jpg,.jpeg,.png" label={text.payment} icon={<FileText size={16} />} /></div></section><button disabled={busy} className="min-h-11 w-full rounded-lg bg-[#173f78] px-4 text-sm font-bold text-white transition-colors hover:bg-[#102e5a] disabled:cursor-wait disabled:opacity-60">{busy ? 'Memproses…' : text.submit}</button></form>}
    {(trackingOnly || tab === 'track') && <section className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-500">Status</p><h2 className="mt-1 text-xl font-bold">{text.track}</h2></div><form onSubmit={track} className="mt-5 grid gap-4 sm:grid-cols-[1fr_1fr_auto]"><input required name="request_number" placeholder={text.number} aria-label={text.number} className="h-11 rounded-lg border-slate-300" /><input required name="tracking_code" placeholder={text.code} aria-label={text.code} className="h-11 rounded-lg border-slate-300" /><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-[#173f78] px-4 text-sm font-bold text-[#173f78] transition-colors hover:bg-blue-50 disabled:opacity-60"><Search size={16} />{text.send}</button></form>{tracking && <section className="mt-5 rounded-lg border border-blue-100 bg-blue-50/60 p-4" aria-live="polite"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-slate-500">{text.number}</p><p className="font-mono font-bold text-[#173f78]">{tracking.request_number ?? '—'}</p></div><div><p className="text-xs text-slate-500">{text.status}</p><p className="font-bold">{tracking.status ?? '—'}</p></div></div><div className="mt-4 border-t border-blue-100 pt-3"><p className="text-xs font-bold text-slate-500">Riwayat</p>{tracking.status_history?.length ? tracking.status_history.map((item, index) => <p key={`${item.status}-${index}`} className="mt-2 text-sm">{item.status} <span className="text-slate-500">{item.created_at ?? ''}</span></p>) : <p className="mt-2 text-sm text-slate-500">{text.empty}</p>}</div></section>}</section>}</div></main></>;
}
