import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router, usePage } from '@inertiajs/react';
import { ArrowDownToLine, ArrowUpFromLine, Boxes, PackageCheck, Search } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { PageProps } from '@/types';

type Range = { id: number; start_number: string; end_number: string; quantity: number; source?: string; received_on?: string; created_at?: string };
type Props = PageProps & { summary: { available: number; assigned: number; stock_in: number; stock_out: number; low_stock_threshold: number }; ranges: { data: Range[] }; filters: { period?: string; from?: string; to?: string } };

export default function Index({ summary, ranges, filters }: Props) {
    const { auth } = usePage<Props>().props;
    const [query, setQuery] = useState('');
    const [period, setPeriod] = useState(filters.period ?? 'all');
    const [threshold, setThreshold] = useState(String(summary.low_stock_threshold));
    const visible = ranges.data.filter((range) => `${range.start_number} ${range.end_number} ${range.source ?? ''}`.toLowerCase().includes(query.toLowerCase()));
    const applyPeriod = (value: string) => { setPeriod(value); router.get('/inventory', { period: value }, { preserveState: true, replace: true }); };
    const saveThreshold = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); router.put('/inventory/low-stock-threshold', { threshold }, { preserveScroll: true }); };
    const cards = [
        { label: 'RFID tersedia', value: summary.available, icon: Boxes, tone: 'text-blue-700 bg-blue-50' },
        { label: 'RFID ditugaskan', value: summary.assigned, icon: PackageCheck, tone: 'text-violet-700 bg-violet-50' },
        { label: 'Total Stock In', value: summary.stock_in, icon: ArrowDownToLine, tone: 'text-emerald-700 bg-emerald-50' },
        { label: 'Total Stock Out', value: summary.stock_out, icon: ArrowUpFromLine, tone: 'text-orange-700 bg-orange-50' },
    ];
    return <AuthenticatedLayout header={<h1 className="text-lg font-semibold">Inventori RFID</h1>}><Head title="Inventori RFID" /><div className="mx-auto max-w-7xl space-y-5">
        <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-semibold tracking-tight">Kesehatan inventori</h2><p className="mt-1 text-sm text-slate-500">Stok dihitung dari qty aktual penerimaan dan pengeluaran.</p></div><span className="text-sm font-semibold text-slate-500">Penerimaan dicatat melalui Catatan Pengadaan</span></div>
        <div className="flex flex-wrap gap-2" aria-label="Filter periode inventori">{[['all','Semua'],['today','Hari ini'],['yesterday','Kemarin'],['week','Minggu'],['month','Bulan']].map(([value, label]) => <button key={value} type="button" onClick={() => applyPeriod(value)} className={`min-h-10 rounded-lg border px-3 text-sm font-semibold ${period === value ? 'border-[#173f78] bg-[#173f78] text-white' : 'border-slate-200 bg-white text-slate-600'}`}>{label}</button>)}<button type="button" onClick={() => setPeriod('custom')} className={`min-h-10 rounded-lg border px-3 text-sm font-semibold ${period === 'custom' ? 'border-[#173f78] bg-[#173f78] text-white' : 'border-slate-200 bg-white text-slate-600'}`}>Custom</button></div>{period === 'custom' && <form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); router.get('/inventory', { period: 'custom', from: data.get('from'), to: data.get('to') }, { preserveState: true, replace: true }); }} className="flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-white p-4"><label className="text-xs font-bold">Dari<input required type="date" name="from" defaultValue={filters.from} className="mt-1 h-10 rounded-lg border-slate-200" /></label><label className="text-xs font-bold">Sampai<input required type="date" name="to" defaultValue={filters.to} className="mt-1 h-10 rounded-lg border-slate-200" /></label><button className="h-10 rounded-lg bg-[#173f78] px-4 text-xs font-bold text-white">Terapkan</button></form>}
        {auth.user?.role === 'admin' && <form onSubmit={saveThreshold} className="flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><label className="grid gap-1 text-xs font-bold text-slate-600">Ambang stok rendah<input required min="0" inputMode="numeric" type="number" value={threshold} onChange={(event) => setThreshold(event.target.value)} className="h-10 w-40 rounded-lg border-slate-200 text-sm" /></label><button className="h-10 rounded-lg border border-slate-300 px-4 text-xs font-bold text-slate-700">Simpan ambang</button><p className="pb-2 text-xs text-slate-500">Notifikasi muncul saat stok tersedia ≤ {summary.low_stock_threshold.toLocaleString('id-ID')} kartu.</p></form>}
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, tone }) => <article key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`grid h-10 w-10 place-items-center rounded-lg ${tone}`}><Icon size={19} /></div><p className="mt-5 text-3xl font-semibold tracking-tight">{value.toLocaleString('id-ID')}</p><p className="mt-1 text-xs font-semibold text-slate-500">{label}</p></article>)}</div>
        <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-center"><div><h3 className="font-bold">Rentang RFID</h3><p className="text-xs text-slate-500">Telusuri nomor awal, akhir, atau sumber.</p></div><label className="relative"><span className="sr-only">Cari rentang RFID</span><Search className="absolute left-3 top-3 text-slate-400" size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari RFID" className="h-10 rounded-lg border-slate-200 pl-9 text-sm" /></label></div>
            {visible.length === 0 ? <p className="p-10 text-center text-sm text-slate-500">Belum ada rentang RFID.</p> : <div><div className="hidden grid-cols-[1fr_1fr_110px_1fr] bg-slate-50 px-5 py-3 text-[11px] font-bold uppercase tracking-wider text-slate-500 sm:grid"><span>Nomor awal</span><span>Nomor akhir</span><span>Jumlah</span><span>Sumber</span></div>{visible.map((range) => <article key={range.id} className="grid gap-3 border-t border-slate-100 px-5 py-4 text-sm first:border-0 sm:grid-cols-[1fr_1fr_110px_1fr]"><p><span className="block text-xs text-slate-400 sm:hidden">Nomor awal</span><b>{range.start_number}</b></p><p><span className="block text-xs text-slate-400 sm:hidden">Nomor akhir</span>{range.end_number}</p><p><span className="block text-xs text-slate-400 sm:hidden">Jumlah</span>{range.quantity}</p><p><span className="block text-xs text-slate-400 sm:hidden">Sumber</span>{range.source ?? '—'}</p></article>)}</div>}
        </section>
    </div></AuthenticatedLayout>;
}
